version: "3"
services:
  app:
    build: .
    ports:
      - "80:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/chatbot"
    restart: on-failure:5
    image: jonatancaraballo/chatbot-api:latest
  mongo:
    image: mongo:5.0.16
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure:5
volumes:
  mongo_data:
