version: "3"
services:
  app:
    build: .
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/chatbot"
      FLASK_APP: "project/app.py"
      PYTHONPATH: "/app"
  mongo:
    image: mongo:5.0.16
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
