version: 2.1

commands:
  create_env_file:
    description: "Create .env file"
    steps:
      - run:
          name: Create .env file
          command: |
            echo "FLASK_RUN_PORT=$FLASK_RUN_PORT" > .env
            echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
            echo "OPENAI_ORG_ID=$OPENAI_ORG_ID" >> .env

jobs:
  build:
    docker:
      - image: cimg/python:3.11.3
    environment:
      AWS_REGION: "ca-central-1"
      CONTAINER_NAME: "chatbot-api"
    steps:
      - checkout
      - create_env_file
      - run:
          name: Install Packages
          command: |
            pip install --upgrade pip pip install --trusted-host pypi.python.org -r requirements.txt
      # Add linter
      - run:
          name: Run Tests
          command: |
            python -m pytest tests/

  deploy:
    docker:
      - image: cimg/base:2023.04
    environment:
      CONTAINER_NAME: "chatbot-api"
    steps:
      - checkout
      - create_env_file
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build the Docker image
          command: docker-compose -f docker-compose.prod.yml build -t $DOCKERHUB_USERNAME/$CONTAINER_NAME:latest
      - run:
          name: Tag and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/$CONTAINER_NAME:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
