version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/aws:2023.04
    environment:
      AWS_REGION: "ca-central-1"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t chatbot-api .
      - run:
          name: Push Docker image to ECR
          command: |
            echo $AWS_REGION | echo $AWS_ACCESS_KEY_ID
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
            docker tag chatbot-api:latest $ECR_REGISTRY/chatbot-api:latest
            docker push $ECR_REGISTRY/chatbot-api:latest
      - add_ssh_keys:
          fingerprints:
          - "e6:b0:dd:bb:2a:ba:c3:ba:a4:0f:91:da:07:2b:e2:71"
      - run:
          name: Deploy to EC2 instance
          command: |
            ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa_e6b0ddbb2abac3baa40f91da072be271 ec2-user@$AWS_INSTANCE_IP "sudo systemctl stop chatbot-api.service && sudo docker pull $ECR_REGISTRY/chatbot-api:latest && sudo systemctl start chatbot-api.service"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main # only deploy when on main
